spring:
  application:
    name: test-eureka

server:
    port: 8762

eureka:
  instance:
    hostname: test2
  client:
    serviceUrl:
      defaultZone: http://test1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
