spring:
  application:
    name: localhost

server:
    port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
